apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose-postgresql.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose-postgresql.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: employeedb
            - name: POSTGRES_PASSWORD
              value: dev
          image: postgres
          name: postgres
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pdb
      restartPolicy: Always
      volumes:
        - name: pdb
          persistentVolumeClaim:
            claimName: pdb
status: {}
---
#service:
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mariadb
spec: 
  selector:
    io.kompose.service: mariadb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432  
  type: NodePort
