apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose-postgresql.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/springboot-restful-net: "true"
    io.kompose.service: springboot-restful-app-postgres
  name: springboot-restful-app-postgres
spec:
  containers:
    - env:
        - name: SPRING_PROFILES_ACTIVE
          value: postgresql
      image: docker.io/library/mini-springboot-restful-webservices-postgres:v0.2
      name: springboot-restful-app-postgres
      ports:
        - containerPort: 8080
          protocol: TCP
  restartPolicy: OnFailure
