version: "3.8"
name: project_springboot_postgres
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: employeedb
    networks:
      net1:
    volumes:
      - pdb:/var/lib/postgresql/data #路徑固定 /var/lib/postgresql/data Ref:https://hub.docker.com/_/postgres
  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile.posgres
      tags:
        - "springboot_postgres:latest"  
    ports:
      - "8091:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql
    networks:
      net1:
    restart: on-failure
    volumes:
      - m2:/root/.m2
networks:
  net1:
    name: "springboot-restful-net"
volumes:
  pdb:
  m2:
