version: "3.8"
name: project_springboot_origin
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: employeedb
    networks:
      net1:
    # volumes:
    #   - db2:/var/lib/mysql #路徑固定 /var/lib/postgresql    
  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=postgresql
    networks:
      net1:
    restart: on-failure
    # volumes:
    #   - m2:/root/.m2
networks:
  net1:
    name: "springboot-restful-net"
# volumes:
#   db2:
#   m2: