apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose-origin.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose-origin.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/springboot-restful-net: "true"
        io.kompose.service: mariadb
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: employeedb
            - name: MYSQL_ROOT_PASSWORD
              value: dev
          image: mariadb
          name: mysqldb
          resources: {}
      restartPolicy: Always
status: {}
---
#service:
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mariadb
spec: 
  selector:
    io.kompose.service: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  
  type: NodePort
