apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose-origin.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/springboot-restful-net: "true"
    io.kompose.service: springboot-restful-webservices
  name: springboot-restful-webservices
spec:
  containers:
    - env:
        - name: SPRING_PROFILES_ACTIVE
          value: origin
      image: docker.io/library/testmysqlcoon-springboot-restful-webservices-mini:v1.1
      name: springboot-restful-webservices
      ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
